live_config_reload = true

[colors.primary]
background = "0x300a24"
foreground = "0xeaeaea"

[env]
ALACRITTY = "yes"
TERM = "xterm-256color"

[font.normal]
family = "Cascadia Mono PL"

[font.offset]
x = 0
y = 2

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.9
