#!/usr/bin/env sh

rm -r ~/.config/emacs || true
ln -s ~/dots/emacs ~/.config/emacs

rm ~/.config/hypr/hyprland.conf || true
ln -s ~/dots/hyprland.conf ~/.config/hypr/hyprland.conf

rm -r ~/.config/quickshell || true
ln -s ~/dots/quickshell ~/.config/quickshell

cd ~/dots/home
# rm ~/.mozilla/firefox/default/search.json.mozlz4
home-manager switch --flake . --impure -L
