#!/usr/bin/env sh

cd ~/dots/home
# rm ~/.mozilla/firefox/default/search.json.mozlz4
home-manager switch --flake . --impure -L

rm ~/.config/emacs || true
ln -s ~/dots/emacs ~/.config/dots/emacs

rm ~/.config/hypr/hyprland.conf || true
ln -s ~/dots/hyprland.conf ~/.config/dots/hyprland.conf
