#!/usr/bin/env sh -e

if [ $1 == "default" ]; then
	xrandr --output DisplayPort-0 --mode 2560x1440 --rate 144.00 --output DisplayPort-1 --mode 2560x1440 --rate 144.00 --right-of DisplayPort-0
elif [ $1 == "left" ]; then
	if [ $2 == "landscape" ]; then
		xrandr --output DisplayPort-1 --rotate normal --pos 0x0 --output DisplayPort-0 --pos 2560x1440
	elif [ $2 == "portrait" ]; then
		xrandr --output DisplayPort-0 --rotate right --pos 0x0 --output DisplayPort-1 --pos 1440x560
	else
		# Disables the right monitor
		xrandr --output DisplayPort-0 --mode 2560x1440 --rate 144.00 --output DisplayPort-1 --off
	fi
elif [ $1 == "right" ]; then
	xrandr --output DisplayPort-1 --mode 2560x1440 --rate 144.00 --output DisplayPort-0 --off
fi
