(require 'package)
(add-to-list 'package-archives '("gnu"   . "https://elpa.gnu.org/packages/"))
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(unless(package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-and-compile
  (setq use-package-always-ensure t
        use-package-expand-minimally t))

(setq backup-directory-alist `(("." . "~/.emacs.d/backups"))
      custom-file (locate-user-emacs-file "configs/custom-vars.el"))
(add-to-list 'custom-theme-load-path "~/.emacs.d/custom-themes")
(add-to-list 'load-path "~/.emacs.d/configs")
(add-to-list 'load-path "~/.emacs.d/configs/languages")
(load custom-file 'noerror 'nomessage)
(put 'narrow-to-region 'disabled nil)

(require 'setup)
(require 'org-config)
(require 'evil-config)
(require 'typst)
(require 'aesthetics)
(require 'dap)
(require 'artemis-mode)
(require 'jasmin)
(require 'number-hl-mode)
(require 'language-checking)
(require 'language-specifics)
(require 'qwerty)
(require 'colemak)

(if (string-equal (system-name) "medusa")
    (progn (qwerty-keymap)
           (setq use-symex-default t))
  (progn (qwerty-keymap)
         (setq use-symex-default t)))

