(add-to-list 'load-path "~/.emacs.d/configs")
(add-to-list 'load-path "~/.emacs.d/configs/languages")
(add-to-list 'custom-theme-load-path "~/.emacs.d/custom-themes")
;; (add-to-list 'load-path "~/.emacs.d/configs/copilot.el")
(put 'narrow-to-region 'disabled nil)

(setq backup-directory-alist `(("." . "~/.emacs.d/backups"))
      custom-file (locate-user-emacs-file "configs/custom-vars.el"))
(load custom-file 'noerror 'nomessage)

(require 'packages-config)
(require 'setup)
(require 'org-config)
(require 'evil-config)
;; (require 'typst)
(require 'aesthetics)
(require 'dap)
(require 'artemis-mode)
(require 'jasmin)
(require 'number-hl-mode)
(require 'language-checking)
(require 'language-specifics)
;; (require 'lsp-booster)
(require 'qwerty)
(require 'colemak)

;; Would go in setup.el, but needs to be loaded last
(if (string-equal (system-name) "medusa")
    (colemak-keymap)
  (qwerty-keymap)
  (setq left-margin-default 80))
